### PR TITLE
 feat/contactModal: created the modal for the contact us section 

### PR DESCRIPTION
**Pull request by olafisoyevince**

### CODE REVIEW

**Comment by olafisoyevince** [comment]
@sammy-code98 Please review

**Review by sammy-code98 — APPROVED** [review]

**Comment by olafisoyevince** [comment]
@sammy-code98 @copy-ninja1 Has this PR been approved?

**Comment by copy-ninja1** [comment]
fix conflict

**Comment by sammy-code98** [comment]
@olafisoyevince  please fix the conflicts and push again

**Pull request closed without merging**
