### PR TITLE
Application UI Refactor Code

### PR DESCRIPTION
**Pull request by KenjxJJ**
Added responsiveness and refactored code.
Have a look.

### CODE REVIEW

**Comment by copy-ninja1** [comment]
Please let's have a meeting when you are free. There are some interesting issues with the changes you made.

**Comment by KenjxJJ** [comment]
Ok. I will soon. Thanks

**Review by mahilday — COMMENTED** [review]
I have fixed the merge conflict so I will close the pr

**Comment by copy-ninja1** [comment]
no please don't close it

**Pull request merged**
